### ISSUE TITLE
Speech history always copying the entry

### ISSUE THREAD

**Issue by vlajna95** [paulber19/NVDAExtensionGlobalPlugin#6]
Whenever you press a key to go to the previous, next or to hear the currently selected entry in the speech history, the entry is copied to the clipboard. Some people refuse to use this functionality of the add-on _only_ because of this somewhat strange behavior, and to me it's completely understandable. 

I solve it adding an `if` statement which allows the call to the `api.copyToClip` method only when the current entry is announced. It probably isn't the best solution for the production version, but it works. ☺ 

speechHistory/__init__.py:104 

```python
		if position == "current":
			if not api.copyToClip(text):
				# Translators: Presented when unable to copy to the clipboard because of an error.
				ui.message(NVDAString("Unable to copy"))
```

Please consider implementing a similar behavior, i.e. the speech history should be copied **only when the current entry is being announced**. 

Thanks 😀

**Comment by paulber19** [comment]
Hi.
Wise remark.
Very surprising that it is only done now because this functionality is 
very old.
Its behavior has been changed in the version under development.
The recording is no longer directly copied to the clipboard.
For the copy in the clipboard, it is now necessary to press twice the 
command gesture of the script which announces the current recording.
Thank you for testing and giving me your opinion.
Best regards
Paul.

**Comment by vlajna95** [comment]
Merci pour une réponse rapide! 😁
